Unit64 cleanup
Stride-Labs/stride pull request #183
Opened 2022-08-11 18:39 UTC by riley-stride

## What is the purpose of the change

1. Replace sf13/cast with our custom fork that checks for overflows
2. Throughout the codebase, use `cast.To__E` from our fork, rather than `cast.To___`. The `E` suffix indicates that we will return `out,err` rather than just `out`, so that we can catch errors! This makes the code more verbose, but safer. 
3. Change a bunch of int64 types to uint64s for extra safety and to reduce the number of casts we must perform

## Brief Changelog

1. Replace cast library in go.mod
2. Replace `cast.ToInt64()` => `cast.ToInt64E` and `cast.ToUint64` => `cast.ToUint64E` and catch any errors
3. Change the following proto struct attributes from uint64 to int64
- depositrecord epochNumber
- UserRedemptionRecord epochNumber
- depositrecord amount
- icaaccount balance
- MsgRedeemStake amt
- epochTracker nextEpochStartTime
- epochTracker duration
- hostZone stakedBal
4. Add a few helpers in utils.go

## Testing and Verifying
unit and integration tests

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? no
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no
  - How is the feature or change documented? n/a

## Notes
- we should refactor `AddDelegationToValidator` at some point to take in only uint amounts, and make a separate fn for `ReduceDelegationFromValidator`; currently, `AddDelegationToValidator` is used to both add and reduce, which is (a) confusing and (b) requires funky casting! IMO this is an issue for another PR since it's a non-trivial change

2022-08-12 23:57 UTC, asalzmann commented
Can you create a pull request with the changes in the fork of the cast library?

2022-08-14 03:10 UTC, vish-stride requested changes
Looks great, really glad we're adding these safety checks!

Some minor formatting (e.g. sprintf) things, but otherwise looks wonderful

2022-08-14 03:10 UTC, vish-stride commented on x/stakeibc/keeper/hooks.go
> +		k.Logger(ctx).Error(fmt.Sprintf("Could not get IBC timeout blocks: %s", err))
%v I believe in the sprintf

2022-08-14 03:10 UTC, vish-stride commented on x/stakeibc/keeper/hooks.go
> +			k.Logger(ctx).Error(fmt.Sprintf("Could not get undelegated balance for host zone %s: %s", zoneInfo.ChainId, error))
second %s should be %v

2022-08-14 03:10 UTC, vish-stride commented on x/stakeibc/keeper/hooks.go
> +			k.Logger(ctx).Error(fmt.Sprintf("Could not get staked balance for host zone %s: %s", zoneInfo.ChainId, err))
second %s should be %v

2022-08-14 03:10 UTC, vish-stride commented on x/stakeibc/keeper/hooks.go
> +			k.Logger(ctx).Error(fmt.Sprintf("Could not get module account balance for host zone %s: %s", zoneInfo.ChainId, error))
second %s should be %v

2022-08-14 03:10 UTC, vish-stride commented on x/stakeibc/keeper/msg_server_redeem_stake.go
> +		k.Logger(ctx).Error("error casting RedeemStake msg.Amount to int64", "err", err)
fmt.Sprintf !

2022-08-14 03:10 UTC, vish-stride commented on x/stakeibc/keeper/msg_server_redeem_stake.go
> +		return nil, sdkerrors.Wrapf(types.ErrInvalidAmount, "invalid amount: %s", err)
fmt.Sprintf for the 2nd arg

2022-08-14 03:10 UTC, vish-stride commented on x/stakeibc/keeper/msg_server_submit_tx.go
> +		return 0, sdkerrors.Wrapf(sdkerrors.ErrInvalidRequest, "Failed to get buffer size: %s", err)
fmt.Sprintf on second arg

2022-08-14 03:10 UTC, vish-stride commented on x/stakeibc/keeper/msg_server_liquid_stake.go
>  		return nil, sdkerrors.Wrapf(sdkerrors.ErrNotFound, "no deposit record for epoch (%d)", strideEpochTracker.EpochNumber)
fmt.Sprintf on second arg

2022-08-14 03:10 UTC, vish-stride commented on x/stakeibc/keeper/msg_server_redeem_stake.go
>  		return nil, sdkerrors.Wrapf(sdkerrors.ErrInvalidCoins, "balance is lower than redemption amount. redemption amount: %d, balance %d: ", msg.Amount, balance.Amount)
fmt.Sprintf on second arg

2022-08-14 03:10 UTC, vish-stride commented on x/stakeibc/keeper/msg_server_submit_tx.go
> +		return 0, sdkerrors.Wrapf(sdkerrors.ErrInvalidRequest, "Failed to get timeout nanos: %s", err)
sdkerrors.Wrapf(sdkerrors

2022-08-14 03:10 UTC, vish-stride commented on x/stakeibc/keeper/msg_server_submit_tx.go
> +			k.Logger(ctx).Error(fmt.Sprintf("error casting latest height to int64: %s", err))
%v

2022-08-14 03:10 UTC, vish-stride commented on x/stakeibc/keeper/unbonding_records.go
> +			k.Logger(ctx).Error(fmt.Sprintf("Error casting validator unbonding amount %d: %s", newUnbondingToValidator[valAddr], err))
%v on err

2022-08-14 03:10 UTC, vish-stride commented on x/stakeibc/keeper/unbonding_records.go
> +			k.Logger(ctx).Error(fmt.Sprintf("Error casting validator staked amount %d: %s", validator.GetDelegationAmt(), err))
%v on err

2022-08-14 03:10 UTC, vish-stride commented on x/stakeibc/keeper/unbonding_records.go
> +				k.Logger(ctx).Error(fmt.Sprintf("Error casting validator staked amount %d: %s", currentAmtStaked, err))
%v on err

2022-08-14 03:10 UTC, vish-stride commented on x/stakeibc/keeper/unbonding_records.go
> +					return sdkerrors.Wrapf(sdkerrors.ErrUnknownRequest, "\t\tCould not convert %d to int64", totalAmtTransferToRedemptionAcct)
fmt.sprintf

2022-08-14 04:17 UTC, asalzmann approved these changes
lgtm - +1 to using Sprintf and a few small comments, but once those are addressed good to merge!

2022-08-14 04:17 UTC, asalzmann commented on x/stakeibc/keeper/unbonding_records.go
> +			curAmtStaked, err := cast.ToInt64E(currentAmtStaked)
why is this being recast to an int64?

2022-08-14 05:01 UTC, riley-stride commented on x/stakeibc/keeper/host_zone.go
> -				absAmt := cast.ToUint64(-amt)
100% agree as discussed offline but let's do it in a new PR to keep this one to type changes, will add to JIRA

2022-08-14 05:08 UTC, riley-stride commented on x/stakeibc/keeper/unbonding_records.go
> +			curAmtStaked, err := cast.ToInt64E(currentAmtStaked)
fixed

2022-08-14 05:09 UTC, riley-stride commented on x/stakeibc/keeper/validator_selection.go
> +			delegateAmt, err := cast.ToUint64E(float64(validator.Weight*finalDelegation) / float64(totalWeight))
we should prob use sdk.dec instead here for consistency across the codebase, wdyt @vishal?

2022-08-14 05:18 UTC, riley-stride commented on x/interchainquery/keeper/keeper.go
> +	if val.LocalHeight.LT(sdk.NewInt(ctx.BlockHeight() - max_age_)) { // this is somewhat arbitrary; TODO: make this better
afaiu it's a comment about unfinished ICQ ttl implementation, has been here from the start

2022-08-14 06:18 UTC, riley-stride commented
@vish-stride can you approve this? you requested a change, I've incorporated them all but it's blocking me until you re-approve

2022-08-14 16:17 UTC, vish-stride commented on proto/records/genesis.proto
> +  uint64 epochNumber = 7;
Normally yes, but I believe the way we serialize/deserialize in the genesis file is by casting to string, so we should be okay here. Later today I’ll get our intended genesis file and we can test this out [](edited-with-Axolo)

2022-08-14 16:18 UTC, vish-stride commented on x/stakeibc/keeper/validator_selection.go
> +			delegateAmt, err := cast.ToUint64E(float64(validator.Weight*finalDelegation) / float64(totalWeight))
Yeah agreed, sdk.dec is better I think. floats are also stochastic so have a high chance of causing a consensus failure later [](edited-with-Axolo)

2022-08-14 16:19 UTC, vish-stride approved these changes
Looks wonderful

2022-08-14 16:19 UTC, merged