TEST 50: make interchainqueries functional
Stride-Labs/stride pull request #22
Opened 2022-05-22 22:18 UTC by riley-stride

# ICQ PR (Draft)

*Summary*: This RP implements ICQ queries so that Gaia can be queries from Stride using the `x/interchainquery` module. See `go/icq` for the relayer implementation and `go/lens` for the Lens client used to listen for and submit queries and transactions on/to Stride/Gaia.

## ICQ
-  In `msg_server.go`, add `QueryBalance` , which defines the callback for ICQ queryAllBalances calls. This is where we parse the results from queries  
- Enable ICQ callbacks in `app.go` by setting the callback handler
- Add handlers for querybalance and submitqueryresponse in `handler.go`
- Add required attributes in `abci.go` passed to icq relayer for query submission on target chain
- Add `callbacks.go`, which defines interface for callback functions passed into ICQ `MakeRequest` calls, to handle results from ICQs
-  In `keeper.go` and `queries.go`, update query_params to request (byte array is cleaner vs string map)
- In `codec.go`, fix the SubmitQueryResponse path (rm v1) and Register interfaces for ICQ methods
- Add ability to submit query responses via the CLI (for testing) in `tx.go`. We’ll want to revoke this prior to launch, but need it for now for testing. 
- In `msgs.go`, add `QueryBalance` message interface 

## Scaffolding

- Add `Dockerfile.icq` which clones the `icq` relayer and runs it, connecting Stride and Gaia. 
- Note that `icq` imports Stride, so the `icq` docker file clones Stride, which makes it fairly bulky (~4GB). Would be nice to find a way for this docker container to import from the Stride container, to reduce bloat.
- Note that Stride and Gaia configs are set in `go/lens`, so if you change them in Docker within the Stride repo, they must accordingly be changed in `go/lens` for the relayer to function properly.
- Add `icq` to docker-compose and mount the `scripts/state` dir

## Misc
- Fix makefile flags (duplicated from other branches)
- Update a few dependencies in `go.mod`
- Add ICQ to readme
- Merged in main
 
## TODO
- [x] Store query results in a local var on ICAAccount. 
     - [X] Storing exchange rate on `query-exchangerate`
     - [X] Storing delegatedBalance on `query-delegatedbalance` @vish-stride see `QueryDelegatedbalance` in `msg_server.go`. For this to work as expected, we just need to have a non-nil delegationAccount before calling query-delegatedbalance.
- [X] - Figure out why ICQ calls sporadically duplicate (it was the relayer deduping)
- [X] Add `scripts/test_icq.sh`
       - Test right now just prints tx logs
- [X] Fund icq relayer light client accounts in `init.sh`

## TESTING
Execute the bats tests with `sh ./scripts/tests/run_all_tests.sh` for a preliminary test of ICQ query-exchangerate and query-delegatedbalance. For a more detailed test of ICQ, run `./scripts/test_icq.sh` and inspect the printed logs manually (would be nice to parse logs and check for expected values; deliberately punting that job to post-MVP)

2022-06-10 14:07 UTC, asalzmann requested changes
Starting to look really good, thanks for pushing through on this tough ticket. Have some comments throughout and `x/interchainquery/keeper/msg_server.go` needs some cleanup (lots of commented code, hanging TODOs - maybe just add a single ticket to clean this file up and add it to comments throughout?).

A few notes
- If you use camelCase for ignite commands like so `ignite scaffold message createPost...` the generated code is slightly more readable. No need to update in this PR, just adding for future reference.
- To untrack `build/`, can you cd into the build dir and run `git rm -rf --cached .` and then `git add . && git commit -m 'untrack build'`?
- Are you thinking we should remove `QueryDelegatedbalance`, `QueryExchangerate`, etc. before launch?

The PR description is very clear and made this easy to review. Thank you!

2022-06-10 14:07 UTC, asalzmann commented on x/interchainquery/keeper/msg_server.go
> +		zone := stakeibctypes.HostZone{
Same comment as above for the `zone`, can we just update the field on `hz`? 

Sorry, I think I may have sent you this code snippet, which was misleading

2022-06-10 14:07 UTC, asalzmann commented on x/interchainquery/keeper/msg_server.go
> +	// query_type := "cosmos.staking.v1beta1.Query/DelegatorDelegations"
rm?

2022-06-10 14:07 UTC, asalzmann commented on x/interchainquery/keeper/msg_server.go
> +			sdk.NewAttribute(types.AttributeKeyHeight, "0"),
add todo to update this

2022-06-10 14:07 UTC, asalzmann commented on x/interchainquery/keeper/msg_server.go
> +		sdk.NewInt(25),
add todo to update this

2022-06-10 14:07 UTC, asalzmann commented on x/interchainquery/keeper/msg_server.go
> +		// TODO get denom dynamically -- is it local or base denom?
add ticket to todos here and below

2022-06-10 14:07 UTC, asalzmann commented on x/interchainquery/keeper/msg_server.go
> +			// Start exchange rate at 1 upon registration
rm this comment

2022-06-10 14:07 UTC, asalzmann commented on x/interchainquery/keeper/msg_server.go
> +		zone := stakeibctypes.HostZone{
same comment as below, rather than creating a new zone is it possible to just update `hz` and write it back?

2022-06-10 14:07 UTC, asalzmann commented on x/interchainquery/keeper/msg_server.go
> +	// TODO replace hardcoded addr with host zone's delegation account
todo

2022-06-10 14:07 UTC, asalzmann commented on x/interchainquery/keeper/msg_server.go
> +	// query_type := "cosmos.bank.v1beta1.Query/AllBalances"
rm?

2022-06-10 14:11 UTC, asalzmann commented on x/interchainquery/client/cli/tx_query_exchangerate.go
> +		Use:   "query-exchangerate [chain-id]",
no actioned needed on this PR, just a styling thing and we can change it in the future

2022-06-10 15:28 UTC, riley-stride commented on app/app.go
> +	app.InterchainqueryKeeper = interchainquerykeeper.NewKeeper(appCodec, keys[interchainquerytypes.StoreKey], app.BankKeeper, app.StakeibcKeeper)
Good point, I will def check for that going fwd. Looks like they are initialized in this case [here](https://github.com/Stride-Labs/stride/pull/22/files/087a314b30f50b4ae4f1b40bfb3934a65e2c682f#diff-0f1d2976054440336a576d47a44a37b80cdf6701dd9113012bce0e3c425819b7R328)

2022-06-10 15:31 UTC, riley-stride commented on .github/workflows/release.yml
> +# This workflow is useful if you want to automate the process of:
I don't think it is, I did not intend to add this file, will remove

2022-06-10 15:47 UTC, riley-stride commented on Dockerfile.icq
> +# TODO remove PAT | access private stride repo using the below personal access token, per https://www.digitalocean.com/community/tutorials/how-to-use-a-private-go-module-in-your-own-project
yes, removed

2022-06-10 15:49 UTC, riley-stride commented on x/interchainquery/client/cli/query.go
> +	// cmd.AddCommand(getInterchainAccountCmd())
rm'd

2022-06-10 15:50 UTC, riley-stride commented on x/interchainquery/client/cli/tx.go
> +		SubmitQueryResponse(),
Adding comment

2022-06-10 15:53 UTC, riley-stride commented on proto/interchainquery/genesis.proto
> +  rpc InterchainAccountFromAddress(QueryServiceInterchainAccountFromAddressRequest) returns (QueryServiceInterchainAccountFromAddressResponse);
yes, rm'd

2022-06-10 15:59 UTC, riley-stride commented on x/interchainquery/client/cli/tx_query_exchangerate.go
> +func CmdQueryExchangerate() *cobra.Command {
Added test-78

2022-06-10 15:59 UTC, riley-stride commented on proto/interchainquery/tx.proto
> +    rpc QueryExchangerate(MsgQueryExchangerate) returns (MsgQueryExchangerateResponse);
Added

2022-06-10 16:10 UTC, vish-stride approved these changes
Overall looks good to me! Aidan's comments were very thorough, I only had a few additional remarks

Really exciting to see this coming together, ICQ was hard but really wonderful end output!

2022-06-10 16:10 UTC, vish-stride commented on x/interchainquery/keeper/abci.go
> +				// TODO add height
i've been using the Jira VSCode extension, it makes it a bit easier to do this! you just right click and hit "create JIRA ticket" and then the ticket also includes the file name + line number

2022-06-10 16:11 UTC, riley-stride commented on x/interchainquery/keeper/keeper.go
> +func NewKeeper(cdc codec.Codec, storeKey sdk.StoreKey, bankKeeper bankkeeper.Keeper, stakeibcKeeper stakeibckeeper.Keeper) Keeper {
Great point, added TEST-80

2022-06-10 16:13 UTC, riley-stride commented on x/interchainquery/keeper/queries.go
> +func (k Keeper) NewQuery(ctx sdk.Context, connection_id string, chain_id string, query_type string, request []byte, period sdk.Int) *types.Query {
for compatibility with recent ICQ release

2022-06-10 16:19 UTC, riley-stride commented on scripts/test_icq.sh
> +#!/bin/bash
TEST-80

2022-06-10 16:25 UTC, riley-stride commented on scripts/init.sh
> +## TODO replace XXX-testnet in lens config with stride_1 and gaia_1 to match env vars here
Added TEST-82

2022-06-10 16:26 UTC, riley-stride commented on scripts/init.sh
> +ICQ_ADDRESS_STRIDE="stride12vfkpj7lpqg0n4j68rr5kyffc6wu55dzqewda4"
TEST-83

2022-06-10 16:28 UTC, riley-stride commented on scripts/test_icq.sh
> +GAIA1_EXEC="docker-compose --ansi never exec -T gaia1 gaiad --home /gaia/.gaiad"
Seems like no, but can't hurt to have it, added to `account_vars.sh` as well (where these lines were copied from)

2022-06-10 16:29 UTC, riley-stride commented on scripts/test_icq.sh
> +$STR1_EXEC tx bank send val1 stride12vfkpj7lpqg0n4j68rr5kyffc6wu55dzqewda4 5000000ustrd \
TEST-83

2022-06-10 16:33 UTC, riley-stride commented on x/interchainquery/keeper/msg_server.go
> +	// TODO should this be Address, not Caller? changed temporarily to suppress error
TODO: change this Caller => Address and run tests again

2022-06-10 16:33 UTC, riley-stride commented on x/interchainquery/keeper/msg_server.go
> +	//TODO Check Denom is valid denom (can you do this for ICS20s?)
Not anymore since we grab the denom from the hostZone

2022-06-10 16:40 UTC, riley-stride commented on x/interchainquery/keeper/msg_server.go
> +		// TODO get denom dynamically
TEST-85

2022-06-10 16:42 UTC, riley-stride commented on x/interchainquery/keeper/msg_server.go
> +		//TODO set this window to something sensible
It's timeout logic, see TEST-79

2022-06-10 16:42 UTC, riley-stride commented on x/interchainquery/keeper/msg_server.go
> +		// TODO change local denom
TEST-85

2022-06-10 16:46 UTC, riley-stride commented on scripts/test_icq.sh
> +$STR1_EXEC tx interchainquery query-balance GAIA cosmos1t2aqq3c6mt8fa6l5ady44manvhqf77sywjcldv uatom \
TODO get this dynamically

2022-06-11 00:42 UTC, riley-stride commented on x/interchainquery/keeper/msg_server.go
> +		delegationAccount := stakeibctypes.ICAAccount{Address: da.Address,
done, much cleaner ty!

2022-06-11 00:42 UTC, riley-stride commented on x/interchainquery/types/msgs.go
> +	// TODO: check from address
yes I believe so

2022-06-11 01:27 UTC, merged