Hieu/upgrade handler (#392)
Stride-Labs/stride pull request #393
Opened 2022-11-25 23:55 UTC by asalzmann

Co-authored-by: Hieu Vu <72878483+hieuvubk@users.noreply.github.com>
Co-authored-by: Jacob Gadikian <jacobgadikian@gmail.com>

Closes: #XXX

## Context and purpose of the change

## Brief Changelog

## Author's Checklist

I have...

- [ ] Run and PASSED locally all GAIA integration tests
- [ ] If the change is contentful, I either:
    - [ ] Added a new unit test OR 
    - [ ] Added test cases to existing unit tests
- [ ] OR this change is a trivial rework / code cleanup without any test coverage

If skipped any of the tests above, explain.

## Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] manually tested (if applicable)
- [ ] confirmed the author wrote unit tests for new logic
- [ ] reviewed documentation exists and is accurate

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes? 
  - [ ] Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`?
  - [ ] This pull request updates existing proto field values (and require a backend and frontend migration)? 
  - [ ] Does this pull request change existing proto field names (and require a frontend migration)?
  How is the feature or change documented? 
      - [ ] not applicable
      - [ ] jira ticket `XXX` 
      - [ ] specification (`x/<module>/spec/`) 
      - [ ] README.md 
      - [ ] not documented

2022-11-26 00:12 UTC, asalzmann commented
I couldn't push to the other branch (https://github.com/Stride-Labs/stride/pull/384) to resolve the linting errors, so created a new one here. There are no changes aside from merging main into the original branch.

2022-11-26 01:26 UTC, sampocs commented
See comments in #384
Also, can we add the [param store key ](https://github.com/Stride-Labs/stride/pull/393/files#diff-aeec7ddb4cf8b7e9e6e57625770d369cce5f377cc350b42c3aca0427bba8dfbcR52-R55) to the instructions in`upgrades/README.md`

2022-11-27 21:26 UTC, faddat approved these changes

2022-11-27 21:27 UTC, faddat commented
Others should have a look also note that I merged in main.

2022-11-27 21:50 UTC, sampocs commented
@asalzmann this diverged from #384 - wanna merge in the recent changes into this one?

2022-11-27 22:15 UTC, asalzmann commented
Merged in. @faddat is it possible for me to get access to the notional stride fork? It would simplify the collaboration workflow (right now my workflow is to merge the notional branch into a separate stride branch, then that stride branch into main, which is a bit cumbersome)

2022-11-27 22:58 UTC, sampocs reviewed
lgtm! Two nit comments

2022-11-27 22:58 UTC, sampocs commented on app/apptesting/test_helpers.go
> +	Context 	sdk.Context
nit: rm

2022-11-27 22:58 UTC, sampocs commented on app/apptesting/test_helpers.go
> +	s.Context = s.App.BaseApp.NewContext(false, tmtypes.Header{Height: 1, ChainID: StrideChainID, Time: time.Now().UTC()})
nit: rm

2022-11-28 11:11 UTC, faddat commented
Yes, I'll add you there.

2022-11-28 11:17 UTC, faddat commented
@asalzmann there's an invite for you at:

https://github.com/notional-labs/stride/invitations

2022-11-28 11:22 UTC, faddat requested changes
This PR should change the import path, I think.  If we'd like to do that separately, please let me know, and I'll un-request these changes :)

2022-11-28 17:47 UTC, sampocs commented
I tested this upgrade locally and it's erroring when trying to add the new authz store key. After removing the authz store upgrade snippet (`Added: []string{authzkeeper.StoreKey}`), the upgrade was successful.

It also appears that the authz store key already exists. I printed `app.keys` from the upgrade handler and `authz` was in the map.

2022-11-28 19:00 UTC, sampocs commented
Also tested it locally using the mainnet state and got the same error
```
state_export-stride-1  | failed to load latest version: failed to load store: initial version set to 1234450, but found earlier version 1234127
```

Removing the authz store upgrade snippet solved this as well.

2022-11-29 15:19 UTC, sampocs commented
@asalzmann was the renaming of `Stride-Labs` → `Stride-labs` intentional?

2022-11-29 19:14 UTC, sampocs commented
I reverted the v4 import path updates - let's do that in a separate PR as we continue to debug this handler. @faddat can you remove the change request?

2022-12-02 02:04 UTC, faddat approved these changes

2022-12-03 01:10 UTC, asalzmann commented on app/app.go
> +	paramsKeeper.Subspace(authz.ModuleName)
Let's leave this out of this upgrade

2022-12-03 01:10 UTC, asalzmann commented on app/upgrades.go
> +		app.SetStoreLoader(AuthzHeightAdjustmentUpgradeStoreLoader(upgradeInfo.Height))
Let's move this to v5

2022-12-03 01:10 UTC, asalzmann commented on app/upgrades/v4/upgrades_test.go
> +				expGenState := authz.DefaultGenesisState()
rm

2022-12-03 01:25 UTC, sampocs commented on app/upgrades/v4/upgrades_test.go
> +				expGenState := authz.DefaultGenesisState()
done

2022-12-03 01:25 UTC, sampocs commented on app/upgrades.go
> +		app.SetStoreLoader(AuthzHeightAdjustmentUpgradeStoreLoader(upgradeInfo.Height))
done

2022-12-03 01:26 UTC, sampocs commented on app/upgrades/v4/README.md
> +# Upgrade v4 Changelog
chatted, leaving this in

2022-12-03 19:29 UTC, merged